server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: publicaciones-autores
              uri: lb://api-publicaciones
              predicates:
                - Path=/api/v1/autores/**
              filters:
                - StripPrefix=2

            - id: publicaciones-libros
              uri: lb://api-publicaciones
              predicates:
                - Path=/api/v1/libros/**
              filters:
                - StripPrefix=2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE