spring:
  application:
    name: ms-openai
  ai:
    openai:
      api-key: YOUR_API_KEY
      model: "gpt-4"
      endpoint: "https://api.openai.com/v1/chat/completions"
      temperature: 0.7 # Adjust temperature for creativity
      max-tokens: 100
      frecuency-penalty: 0.1

server:
  port: 8080
