server:
  port: 0

spring:
  application:
    name: servicio-notificaciones
  datasource:
    #url: jdbc:postgresql://localhost:5432/notificaciones_db
    #username: postgres
    #password: qwerty123
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/notificaciones_db?user=root&password=
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE